/var/spool/slurmd/job4850605/slurm_script: line 21: nvcc: command not found
/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/distributed/launch.py:208: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  main()
W0724 15:28:13.855824 140736413464384 torch/distributed/run.py:779] 
W0724 15:28:13.855824 140736413464384 torch/distributed/run.py:779] *****************************************
W0724 15:28:13.855824 140736413464384 torch/distributed/run.py:779] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0724 15:28:13.855824 140736413464384 torch/distributed/run.py:779] *****************************************
/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torchvision/io/image.py:11: UserWarning: Failed to load image Python extension: libtorch_cuda_cu.so: cannot open shared object file: No such file or directory
  warn(f"Failed to load image Python extension: {e}")
/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/nn/modules/transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/nn/modules/transformer.py:307: UserWarning: enable_nested_tensor is True, but self.use_nested_tensor is False because encoder_layer.norm_first was True
  warnings.warn(f"enable_nested_tensor is True, but self.use_nested_tensor is False because {why_not_sparsity_fast_path}")
wandb: Currently logged in as: ni-eminen (matias_) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.21.0
wandb: Run data is saved locally in ./checkpoint/savi_bev_params_test/models/wandb/run-20250724_152822-savi_bev_params_test-4850605
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run savi_bev_params_test-4850605
wandb: ‚≠êÔ∏è View project at https://wandb.ai/matias_/SlotFormer
wandb: üöÄ View run at https://wandb.ai/matias_/SlotFormer/runs/savi_bev_params_test-4850605
/projappl/project_2014099/new-slotformer-bev/nerv/nerv/training/method.py:148: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.grad_scaler = torch.cuda.amp.GradScaler()
/projappl/project_2014099/new-slotformer-bev/nerv/nerv/training/method.py:148: FutureWarning: `torch.cuda.amp.GradScaler(args...)` is deprecated. Please use `torch.amp.GradScaler('cuda', args...)` instead.
  self.grad_scaler = torch.cuda.amp.GradScaler()
/projappl/project_2014099/new-slotformer-bev/nerv/nerv/training/method.py:646: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckp = torch.load(ckp_path, map_location='cpu')
/projappl/project_2014099/new-slotformer-bev/nerv/nerv/training/method.py:646: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  ckp = torch.load(ckp_path, map_location='cpu')
Eval epoch 0, rank 1:   0%|          | 0/1 [00:00<?, ?it/s]Eval epoch 0, rank 0:   0%|          | 0/1 [00:00<?, ?it/s]/projappl/project_2014099/new-slotformer-bev/slotformer/bev_slots/models/savi.py:100: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False, dtype=torch.float16):
/projappl/project_2014099/new-slotformer-bev/slotformer/bev_slots/models/savi.py:100: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(enabled=False, dtype=torch.float16):
Eval epoch 0, rank 1: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:09<00:00,  9.69s/it]Eval epoch 0, rank 0: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:09<00:00,  9.68s/it]Eval epoch 0, rank 1: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:09<00:00,  9.69s/it]
Eval epoch 0, rank 0: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:09<00:00,  9.69s/it]
Train epoch 0, rank 0: 0it [00:00, ?it/s]Train epoch 0, rank 1: 0it [00:00, ?it/s]Train epoch 0, rank 0: 0it [00:00, ?it/s]
Train epoch 0, rank 1: 0it [00:00, ?it/s]
[rank0]: Traceback (most recent call last):
[rank0]:   File "scripts/train.py", line 115, in <module>
[rank0]:     main(params)
[rank0]:   File "scripts/train.py", line 77, in main
[rank0]:     method.fit(
[rank0]:   File "/projappl/project_2014099/new-slotformer-bev/nerv/nerv/training/method.py", line 194, in fit
[rank0]:     self.training_epoch()
[rank0]:   File "/projappl/project_2014099/new-slotformer-bev/nerv/nerv/training/method.py", line 215, in training_epoch
[rank0]:     for batch_idx, batch_data in enumerate(self.iter_train_loader):
[rank0]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank0]:     data = self._next_data()
[rank0]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
[rank0]:     return self._process_data(data)
[rank0]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
[rank0]:     data.reraise()
[rank0]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
[rank0]:     raise exception
[rank0]: IndexError: Caught IndexError in DataLoader worker process 0.
[rank0]: Original Traceback (most recent call last):
[rank0]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
[rank0]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank0]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
[rank0]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank0]:   File "/projappl/project_2014099/new-slotformer-bev/slotformer/bev_slots/datasets/bevdataset.py", line 188, in __getitem__
[rank0]:     info = self.scenario_infos[idx]
[rank0]: IndexError: list index out of range

[rank1]: Traceback (most recent call last):
[rank1]:   File "scripts/train.py", line 115, in <module>
[rank1]:     main(params)
[rank1]:   File "scripts/train.py", line 77, in main
[rank1]:     method.fit(
[rank1]:   File "/projappl/project_2014099/new-slotformer-bev/nerv/nerv/training/method.py", line 194, in fit
[rank1]:     self.training_epoch()
[rank1]:   File "/projappl/project_2014099/new-slotformer-bev/nerv/nerv/training/method.py", line 215, in training_epoch
[rank1]:     for batch_idx, batch_data in enumerate(self.iter_train_loader):
[rank1]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
[rank1]:     data = self._next_data()
[rank1]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1344, in _next_data
[rank1]:     return self._process_data(data)
[rank1]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1370, in _process_data
[rank1]:     data.reraise()
[rank1]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/_utils.py", line 706, in reraise
[rank1]:     raise exception
[rank1]: IndexError: Caught IndexError in DataLoader worker process 0.
[rank1]: Original Traceback (most recent call last):
[rank1]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 309, in _worker_loop
[rank1]:     data = fetcher.fetch(index)  # type: ignore[possibly-undefined]
[rank1]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
[rank1]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank1]:   File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 52, in <listcomp>
[rank1]:     data = [self.dataset[idx] for idx in possibly_batched_index]
[rank1]:   File "/projappl/project_2014099/new-slotformer-bev/slotformer/bev_slots/datasets/bevdataset.py", line 188, in __getitem__
[rank1]:     info = self.scenario_infos[idx]
[rank1]: IndexError: list index out of range

W0724 15:29:57.177814 140736413464384 torch/distributed/elastic/multiprocessing/api.py:858] Sending process 431000 closing signal SIGTERM
E0724 15:29:57.342965 140736413464384 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 1 (pid: 431001) of binary: /projappl/project_2014099/newenvslot/bin/python
Traceback (most recent call last):
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/distributed/launch.py", line 208, in <module>
    main()
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/typing_extensions.py", line 2853, in wrapper
    return arg(*args, **kwargs)
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/distributed/launch.py", line 204, in main
    launch(args)
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/distributed/launch.py", line 189, in launch
    run(args)
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/distributed/run.py", line 892, in run
    elastic_launch(
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 133, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/MAHTI_TYKKY_NoejaWK/miniforge/envs/env1/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
scripts/train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-24_15:29:57
  host      : g1101.mahti.csc.fi
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 431001)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
